### ISSUE TITLE
getting this error running TC03-identifyElements.spec.js

### ISSUE THREAD

**Issue by dborde** [QAMilestoneAcademy/Cypress#1]
CONTAINS
No articles are here... yet.
0
ASSERT
expected { Object (length, prevObject, ...) } to be visible
CypressError: Timed out retrying: Expected to find content: 'No articles are here... yet.' but never did.

**Comment by QAMilestoneAcademy** [comment]
We are asserting that 'Favorited Articles' tab contains no article and that 'No articles are here... yet.' text should appear. But probably you have some favorited articles there. 

You could instead verify that the count of favorited articles has decreased by 1 after unmarking an article as favorite. This might help you achieve it: [Cypress - Then command](https://www.youtube.com/watch?v=OA0PXRf7bo8)
